#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

if [ $# -eq 1 ]
then
    VERSION="$1"
else
    VERSION=$(cat $DIR/helpspot/helpspot/version.txt)
fi

echo "Building AzureLiveLookup Version: $VERSION"

git tag -d $VERSION
git push origin :refs/tags/$VERSION
git tag $VERSION && git push origin $VERSION
